### ISSUE TITLE
 Email Verification

### ISSUE THREAD

**Issue by NoahDR17** [NoahDR17/Recipe-Blog#8]
As a **site owner**, I want **users to verify their email when registering**, so that **valid accounts are being used.*.

## Acceptance Criteria: 
- After registration, users receive a verification email with a link.
- Clicking the verification link successfully activates the user’s account.
- If users try to log in without verifying their email, they receive a prompt to verify their email first.
- The verification email contains a functional link and clear instructions.

## Tasks: 
- [ ] Configure email verification in Django Allauth settings.
- [ ] Set up email template for verification emails.
- [ ] Ensure that users are prompted to verify their email after registering.
- [ ] Create a view to handle email verification and confirmation process.
- [ ] Redirect users to the appropriate page after email verification (e.g., login page).
